# Generated by Django 4.2.1 on 2023-05-26 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspection_id', models.IntegerField(primary_key=True, serialize=False)),
                ('certificate_no', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=50, null=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='InspectionCenter',
            fields=[
                ('center_id', models.IntegerField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('owner_info', models.CharField(max_length=50)),
                ('owner_type', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_val', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('email', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('plate_no', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('registration_cert_no', models.CharField(max_length=20)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('usage_purpose', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('upload_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('upload_date', models.DateField(blank=True, null=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspectioncenter')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('result', models.CharField(max_length=50)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspectioncenter')),
                ('inspection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspectioncenter',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
    ]
