# Generated by Django 4.2.1 on 2023-05-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='inspectioncenter',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='inspectioncenter',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='inspectionrecord',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='inspectionrecord',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_updated',
        ),
    ]
