# Generated by Django 4.2.1 on 2023-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_inspection_date_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimarySequence',
        ),
    ]
